debug: false
management.endpoints.web.exposure.include: "*" # actuator ? ??? ???? ?? ??.

logging:
  level:
    com.deploykube.board: debug # ??? ??? ???? ??
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA ??? query ??? ????. ??? ???? ????

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: gamza
    password: 1394
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated